samba_path = "/usr/bin/samba-tool"
server_name = "galleon"
home_dirs_path = "/home/userdata/users"
nt_domain_name = "FERRPANC"
pool_path = "/home/userdata/groups"
pool_owner = "Domain Admins"
winbind_separator = "+"
