[package]
name = "fp_tools"
version = "0.4.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
mysql = { version = "26.0.0", features = ["chrono"] }
sudo = "0.6.0"